version: "3.8"

services:
  web:
    image: kooldev/php:8.2-nginx
    volumes:
      - .:/app
    ports:
      - "8000:80"
    networks:
      - todo-app
  todo-app-db:
    container_name: todo-app-db
    image: mysql:8.0
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: todo-app-db
      MYSQL_ROOT_PASSWORD: password
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password",
      ]
    volumes:
      - ./vendor/data/:/var/lib/mysql/
    networks:
      - todo-app

networks:
  todo-app:
